service: calcutta-admin-management

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${self:custom.stage}
    APP_ENV: ${self:custom.stage}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST:
      Fn::ImportValue: calcutta-db-ec2-${self:custom.stage}-dns-address
    DB_PORT: 1433

functions:
  getLegacyLeagues:
    handler: functions/getLegacyLeagues.getLegacyLeagues
    vpc:
      securityGroupIds:
        - Fn::ImportValue: calcutta-lambdaSG-${self:custom.stage}
      subnetIds:
        - Fn::ImportValue: calcutta-lambda-subnet1-${self:custom.stage}
        - Fn::ImportValue: calcutta-lambda-subnet2-${self:custom.stage}
        - Fn::ImportValue: calcutta-lambda-subnet3-${self:custom.stage}
    events:
      - http:
          path: getLegacyLeagues
          method: get
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - x-cognito-token

resources:
  - ${file(resources/cognito-authorizer.yml)}