language: node_js
node_js:
- stable
branches:
  only:
  - master
  - develop
notifications:
  email:
    on_failure: always
    on_success: always
deploy_service_job:
  cache: &1
    directories:
    - node_modules
    - "${SERVICE_PATH}/node_modules"
  install: &2
  - npm install -g serverless
  - travis_retry npm install
  - cd ${SERVICE_PATH}
  - travis_retry npm install
  - cd -
  script: &3
  - cd ${SERVICE_PATH}
  - echo ${TEST_VAR}
  - serverless deploy -s ${STAGE_NAME}
  - cd -
environments:
- &5
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
- &4
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}
jobs:
  include:
  - cache: *1
    install: *2
    script: *3
    name: Deploy Game API
    if: type = push AND branch = develop
    env:
    - SERVICE_PATH='services/games'
    - STAGE_NAME=dev
    - *4
    - *SECRETS_DEV
  - cache: *1
    install: *2
    script: *3
    name: Deploy Game API
    if: type = push AND branch = master
    env:
    - SERVICE_PATH='services/games'
    - STAGE_NAME=prod
    - *5
env:
  dev: &SECRETS_DEV
  - secure: CxvZRzteP+wdHNp+vjvt8p6sGuQFeiy7eHvqU64K7TE3NmtGVLnITigPQa6jx8YpDYJuJHc6FioRFenPF3OkTm8VGi2nEumYfLO5v6UzWlmDNPGEl38CQDS9b2f4O5Isc4IgVzPRHfjrDoWXaEWxnICDdwQDLuze0DAtSXOmGnWIG0KGVJ17cac/STdxS1HIXWXskvczGtwsGZrzQ4o8geskRgygn5keWbGui+u/Ypy0I8YDU2tJepAKzFzwGWu/PYkxdkYcR2jDXUrjai5/qcoYclN7pGOvtEUm3cZoNE5Nfghh2mDAjZ5k4qCS5dThT25+gwKwfT8sgAbzoFWyDnRVZscpnNPH1Fjdbv6qwM6yj2HQbsr2oUBCGcrrj04G4Mr/CDG+REKFmCe2N4+LmWCycSMuZeahYpfQPhLa2GCcFgDsw1jTvIakkOk7tJOmThxuG+daaYEGK3HGNqw5druBmynSXaHaU6tqqhTdTgMQyFfM4uOSle6PMt/aRID60ZEK+ZLb11GFbIBRzDpMaShYTJ2proxVAB74yzrqruzOxVAJN+1iiqIiKjqYJt0PofbXA2gSiXieZea3ImjeHuft3fRo30Gk4R6l1aAsnQIDS7luR4fB/r0Wn0wMUtaO+smTZUqKkmVMu7r+M8oqkHy9bC1Je5cUraX5VihfYuQ=
  - secure: hqEIds38XcDIb+t8/2lz9LI/aXM/ynnfYquR0OK0lJRTvH7aRonbQouu/Vewy/QxtUxxJmeI6jj4PF2Xl4ESOGYdshYvPQ+z5gtopCVFRaarpYXgjQJiO61CfJ/ZYlYTUDPYRJtYzbLd28e+QRZsuwNYzxJfvlU+Lr7xs4dRnXEDfpa0pnR3d5psV/Y8sLybAmN0NtmxYrYaG223sFJRNNDDHcsvj7XYe9VuMQXL4jFRKc82g8E7wmve5OJyXSfYF+ey7N1R0PQEkZijJrsaaGSBrQRQxyUSRvnk6hpG9+xO5gRoGaVghYzVcK0r26/l8giZEFutnluGQ5UZwYxeze61agwqUs4Gx2naYCMN9BXdyYXKnb6QW3n+NXzh8Bp3v4l0WsvYDO4EdnfZ6W899egR2HlxNmvA76cX5+Z0fqV2iBLPMnYtdyupRiLla+5bMHepaqoSqFyP3ASb7cl/L2CfWOx0YScSuDVlt8m47IlgofDdJnA21pP0Yu7kVRa3fQF6wWRAdyLJWiJDlpcKAf4wQ7WIO7Jm9F6ItZZu/Snkfz0qgWNdOwYCMNUwrVwBDQcWSafrkh67fIb6HaJSOedg67SDhjrbrDAA1PlCvGSyTEH3Qi2r95u4j1zdI7QS/mOxdl9jrsRR8riem9UdpFMJuuN5/OetKug0AwwgbnM=
  - secure: JqGLe44IQ7ysYW3kU7cCKzdt6WC4Spi8X8FN3xezcywzxnRwPzL5zYYLAydE7EAlvj7vPl1UrQf0j6riPKfIxktUgfe5tTnpDbFjdoaZJsfyHvDuvl8h5AnJU9Bzv8S6yi5RYuVHST96UkIVteJeyamNOb/yar1xkKVrivvGs/uHX6Sp984BfTPVijYwrHM21qWXE3z2tHZMQ/MSFIcSP6XmP0n+s3ECwhPWbU+gzyefosGwTGYGh2dHUjQM2uwQ+submuoG8ISg2rUUMXb84+5UxYq7XbHK6+kf8gohpLxUMmCZeNHa2cP1pBztczjd/Hp2DxHI+c2hEqVjGRUlv+qR6MpExGyhYv7BxJQkLkL/bbH3xH6CyF34UrII0X+vecHGQ9FeU88a/1Xzln+/pwngRVPxduCVRFZd3cnymrHmFS96mHjcOwZ7/0oMrOgqUELhAfRgigeOSgcruuju31LjIZWwQtJ5EAoyktg7gnPImqaGfp7XwTtDoeUqZlyfDrmnChVMM7V0hbo86j9Dy2DViNIdJbmuzWtSC72IE/6kFHdo4aNsulZjLYEmrjarqGMdB63nIfZxC4rogUiH+cst6RYaWGYqeNj/QBA7l8sDGIV72E6+XvjKkXIVYZAK4Zd+Poma32i0I2dRoPdd1BiboCAUBISEeKABjqqMotc=
  - secure: T+p+pLSOdugV7c1VbRUhYgFo9GYQ7U9lHgd+8ep78NDAP3aQxLQ39rLKczRh8jlKGWrnOB75KODgWlcbnmkjy1BFpUhc3ilcJ6u+hisfKzIC6lNphX/OYG2UYCjNOQpkLHoaNt2WP2TDELXSzOtEQ9fkBb1YkeBC5RXnL6xdPP2wtVd9tWDvJWFVkDGa5nOF4W+rWU6Iq1sko2xajTh3v3bhCweUfLU52ps22sv6pHp7sW5Yqrr5l3tZxKfcfEwE3ekg//mB2x9eUZyAgWgP98gb641iscSrvKH+bNL3sstwf+Dsk2TK963WHhfBKc7E7hMzCxGcWIba8ViquCx4sFnekEZpsbtWx8ELy9nqzGth9Lu3LxaEVnuge2EhiQSzazfVK+5AICTMh65zsmzjJ6vq0tDyPbDMiq4sERGjq3ogSMcZNPDdQxMKNhjrRkYLd0dsy6LWMfX8esjtKb1Q98MTdvWR28WjNyQRxo7DvJI7hGoFI9Luu31aTCPo9URj9HY/dlPGV99m1lY5jnSrqSmmx+2K1P24joTnvomlHNz4l5tzhJRS+UvVIeUXKbP9Ob8DOJtzA4OL4B1XuKV4yggdk7lx0il5T3I0Ui2FU7rsqMwYJRJmajNmEREQgtG/uEW/Nm76Gw91OfcbZwkCIXFwYjIYYPuKqg6iokfPzqc=
  - TEST_VAR: 'hey dummy'