service: calcutta-admin-api-games

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
        
provider:
  name: aws
  runtime: nodejs16.x
  timeout: 10
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${self:custom.stage}
    APP_ENV: ${self:custom.stage}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST:
      Fn::ImportValue: calcutta-db-ec2-${self:custom.stage}-dns-address
    DB_PORT: 1433
  vpc:
    securityGroupIds:
      - Fn::ImportValue: calcutta-lambdaSG-${self:custom.stage}
    subnetIds:
      - Fn::ImportValue: calcutta-lambda-subnet1-${self:custom.stage}
      - Fn::ImportValue: calcutta-lambda-subnet2-${self:custom.stage}
      - Fn::ImportValue: calcutta-lambda-subnet3-${self:custom.stage}

functions:
  getSportOptions:
    handler: functions/getSportOptions.getSportOptions
    events:
      - http:
          path: getSportOptions
          method: get
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - x-cognito-token

  getGamesMetadata:
    handler: functions/getGamesMetadata.getGamesMetadata
    events:
      - http:
          path: getGamesMetadata/{sportId}/{date}
          method: get
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - x-cognito-token

  getGamesBySportId:
    handler: functions/getGames.getGamesBySportId
    events:
      - http:
          path: getGamesBySportId/{sportId}/{date}
          method: get
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - x-cognito-token

  updateScores:
    handler: functions/updateScores.updateScores
    events:
      - http:
          path: updateScores
          method: post
          integration: lambda
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors:
            origin: '*'
            headers:
              - Content-Type
              - x-cognito-token


resources:
  - ${file(resources/cognito-authorizer.yml)}