Resources:
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 300
      IdentitySource: method.request.header.x-cognito-token
      Name: cognito_authorizer
      RestApiId: { "Ref" : "ApiGatewayRestApi" }
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - ${env:${self:custom.stage}.USER_POOL_ARN}