name: Stage

on:
  push:
    branches: develop

jobs:
  games_service:
    name: Deploy games service API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g serverless
      - run: npm install
      - run: |
          rm -rf utilities/* resources/*
          cd services/games
          npm install
          serverless deploy -s $STAGE_NAME

  tournament_service:
    name: Deploy tournament service API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g serverless
      - run: npm install
      - run: |
          cd services/tournament
          npm install
          serverless deploy -s $STAGE_NAME
  
env:
  STAGE_NAME: dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  USER_POOL_ARN: ${{ secrets.USER_POOL_ARN_DEV }}